### ISSUE TITLE
SSL Certificate issue

### ISSUE THREAD

**Issue by shura-v** [meshchaninov/alfred-translate-workflow#3]
I have an issue with python3 when using workflow:

```
[22:07:21.937] ERROR: Translate[Script Filter] Code 1: Traceback (most recent call last):
  File "/Users/super/Documents/alfred/Alfred.alfredpreferences/workflows/user.workflow.73A9E2D9-E047-4EC4-B836-7F3ECDADDD74/./main.py", line 225, in <module>
    out_lang).get_translation(' '.join(text_list))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/super/Documents/alfred/Alfred.alfredpreferences/workflows/user.workflow.73A9E2D9-E047-4EC4-B836-7F3ECDADDD74/./main.py", line 203, in get_translation
    return self._parse_response(self._get_request(text))
                                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/super/Documents/alfred/Alfred.alfredpreferences/workflows/user.workflow.73A9E2D9-E047-4EC4-B836-7F3ECDADDD74/./main.py", line 191, in _get_request
    conn.request("GET", path, headers=headers)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 1286, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 1332, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 1281, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 1041, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 979, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 1458, in connect
    self.sock = self._context.wrap_socket(self.sock,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ssl.py", line 517, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ssl.py", line 1075, in _create
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ssl.py", line 1346, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1002)
```

**Comment by meshchaninov** [comment]
Can you please write your mac os specs?
- OS version
- Mac model
- Alfred version
